/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentSettledEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type InlineExtension,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
// Native subagents — explicit public surface (test-only underscore internals
// like _resetBackgroundRegistryForTests are deliberately excluded; package root
// promotes only the three core types).
export type {
	BackgroundLogEvent,
	BackgroundLogRecord,
	BackgroundLogTail,
	BackgroundRegistry,
	BackgroundTask,
	BackgroundUsage,
	BunApi,
	BunProcessRunnerOptions,
	BunReadableStream,
	BunShell,
	BunShellResult,
	BunSpawnOptions,
	BunSubprocess,
	CollectedStream,
	DisplayItem,
	ExperimentResult,
	ExperimentRow,
	ExperimentStatus,
	ExperimentsUi,
	ExperimentToolName,
	GitResult,
	RegistryFile,
	ResearchModeOptions,
	ShellOptions,
	ShellResult,
	StreamPump,
	SubagentEvent,
	SubagentEventListener,
	SubagentMode,
	SubagentResult,
	SubagentRunner,
	SubagentRunRequest,
	SubagentSettingsReader,
	SubagentSpec,
	SubagentToolDetails,
	SubagentToolInput,
	SubagentToolOptions,
	SubagentUsage,
	TaskStatus,
	WorktreeCreateResult,
	WorktreeDiffResult,
} from "./subagent/index.ts";
export {
	addExperiment,
	appendExperimentLogEvent,
	BG_CUSTOM_MESSAGE_TYPE,
	BG_LOG_MAX_BYTES,
	BG_LOG_MAX_RECORDS,
	backgroundLogPath,
	buildStatusInjection,
	cherryPickFromBranch,
	clearBackgroundDashboard,
	clearBackgroundLogOverlay,
	clearDashboard,
	collectStream,
	createBunProcessRunner,
	createEmptyUsage,
	createExperimentToolDefinitions,
	createExperimentTools,
	createStreamPump,
	createSubagentTool,
	createSubagentToolDefinition,
	createWorktree,
	currentHead,
	diffVsParent,
	EXPERIMENT_TOOL_NAMES,
	ExperimentRegistryLockError,
	ensureExperimentLog,
	experimentDir,
	experimentsDir,
	formatTokens,
	formatUsageStats,
	getBackgroundRegistry,
	getBun,
	getDisplayItems,
	getExperiment,
	getPiInvocation,
	getSubagentResultOutput,
	isBunRuntime,
	isFailedSubagentResult,
	isGitRepo,
	listExperiments,
	listWorktrees,
	logPath,
	makeExperimentId,
	PER_TASK_OUTPUT_CAP,
	pruneWorktrees,
	REGISTRY_VERSION,
	RegistryLockError,
	ResearchModeTracker,
	readBackgroundLogTail,
	readRegistry,
	removeWorktree,
	renderBackgroundLines,
	renderBackgroundLogLines,
	renderBackgroundPill,
	renderDashboardLines,
	renderExperimentsStatusPill,
	renderSubagentCall,
	renderSubagentResult,
	resolveModelOverrides,
	runGit,
	runShell,
	runShellLine,
	shouldRegisterExperimentTools,
	shouldRegisterSubagentTool,
	showBackgroundDashboard,
	showBackgroundLogOverlay,
	showDashboard,
	squashSinceParent,
	startBackgroundSubagent,
	subagentSchema,
	UI_KEYS,
	updateExperiment,
	withWriteLock,
	writeRegistry,
} from "./subagent/index.ts";
